"""Add owners and maintainers table

Revision ID: 6fbe44320a21
Revises: aca3c96f4a12
Create Date: 2022-09-07 20:56:28.963484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbe44320a21'
down_revision = 'aca3c96f4a12'
branch_labels = None
depends_on = None


def upgrade():
    app_schema = 'flaskapp'
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintainers',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [f'{app_schema}.groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [f'{app_schema}.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    schema=app_schema
    )
    op.create_table('owners',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [f'{app_schema}.groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [f'{app_schema}.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    schema=app_schema
    )
    op.drop_constraint('groups_owner_id_fkey', 'groups', schema=app_schema, type_='foreignkey')
    op.drop_column('groups', 'owner_id', schema=app_schema)
    # ### end Alembic commands ###


def downgrade():
    app_schema = 'flaskapp'
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True), schema=app_schema)
    op.create_foreign_key('groups_owner_id_fkey', 'groups', 'users', ['owner_id'], ['id'], source_schema=app_schema, referent_schema=app_schema)
    op.drop_table('owners', schema=app_schema)
    op.drop_table('maintainers', schema=app_schema)
    # ### end Alembic commands ###
