"""Add created by and updated by columns

Revision ID: 9f71141d96c1
Revises: 6fbe44320a21
Create Date: 2022-09-10 14:50:29.955177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f71141d96c1'
down_revision = '6fbe44320a21'
branch_labels = None
depends_on = None


def upgrade():
    app_schema = 'flaskapp'

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema=app_schema)
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema=app_schema)
    op.add_column('groups', sa.Column('created_by', sa.String(), nullable=True), schema=app_schema)
    op.add_column('groups', sa.Column('updated_by', sa.String(), nullable=True), schema=app_schema)
    op.drop_column('groups', 'updated', schema=app_schema)
    op.drop_column('groups', 'created', schema=app_schema)
    op.add_column('maintainers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema=app_schema)
    op.add_column('maintainers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema=app_schema)
    op.add_column('maintainers', sa.Column('created_by', sa.String(), nullable=True), schema=app_schema)
    op.add_column('maintainers', sa.Column('updated_by', sa.String(), nullable=True), schema=app_schema)
    op.drop_column('maintainers', 'updated', schema=app_schema)
    op.drop_column('maintainers', 'created', schema=app_schema)
    op.add_column('owners', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema=app_schema)
    op.add_column('owners', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema=app_schema)
    op.add_column('owners', sa.Column('created_by', sa.String(), nullable=True), schema=app_schema)
    op.add_column('owners', sa.Column('updated_by', sa.String(), nullable=True), schema=app_schema)
    op.drop_column('owners', 'updated', schema=app_schema)
    op.drop_column('owners', 'created', schema=app_schema)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema=app_schema)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema=app_schema)
    op.add_column('users', sa.Column('created_by', sa.String(), nullable=True), schema=app_schema)
    op.add_column('users', sa.Column('updated_by', sa.String(), nullable=True), schema=app_schema)
    op.drop_column('users', 'updated', schema=app_schema)
    op.drop_column('users', 'created', schema=app_schema)
    op.add_column('users_groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema=app_schema)
    op.add_column('users_groups', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema=app_schema)
    op.add_column('users_groups', sa.Column('created_by', sa.String(), nullable=True), schema=app_schema)
    op.add_column('users_groups', sa.Column('updated_by', sa.String(), nullable=True), schema=app_schema)
    op.drop_column('users_groups', 'updated', schema=app_schema)
    op.drop_column('users_groups', 'created', schema=app_schema)
    # ### end Alembic commands ###


def downgrade():
    app_schema = 'flaskapp'

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_groups', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.sql.func.now()), schema=app_schema)
    op.add_column('users_groups', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema=app_schema)
    op.drop_column('users_groups', 'updated_by', schema=app_schema)
    op.drop_column('users_groups', 'created_by', schema=app_schema)
    op.drop_column('users_groups', 'updated_at', schema=app_schema)
    op.drop_column('users_groups', 'created_at', schema=app_schema)
    op.add_column('users', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.sql.func.now()), schema=app_schema)
    op.add_column('users', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema=app_schema)
    op.drop_column('users', 'updated_by', schema=app_schema)
    op.drop_column('users', 'created_by', schema=app_schema)
    op.drop_column('users', 'updated_at', schema=app_schema)
    op.drop_column('users', 'created_at', schema=app_schema)
    op.add_column('owners', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.sql.func.now()), schema=app_schema)
    op.add_column('owners', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema=app_schema)
    op.drop_column('owners', 'updated_by', schema=app_schema)
    op.drop_column('owners', 'created_by', schema=app_schema)
    op.drop_column('owners', 'updated_at', schema=app_schema)
    op.drop_column('owners', 'created_at', schema=app_schema)
    op.add_column('maintainers', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.sql.func.now()), schema=app_schema)
    op.add_column('maintainers', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema=app_schema)
    op.drop_column('maintainers', 'updated_by', schema=app_schema)
    op.drop_column('maintainers', 'created_by', schema=app_schema)
    op.drop_column('maintainers', 'updated_at', schema=app_schema)
    op.drop_column('maintainers', 'created_at', schema=app_schema)
    op.add_column('groups', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.sql.func.now()), schema=app_schema)
    op.add_column('groups', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema=app_schema)
    op.drop_column('groups', 'updated_by', schema=app_schema)
    op.drop_column('groups', 'created_by', schema=app_schema)
    op.drop_column('groups', 'updated_at', schema=app_schema)
    op.drop_column('groups', 'created_at', schema=app_schema)

    op.alter_column('users_groups', 'created', nullable=True, server_default=None, schema=app_schema)
    op.alter_column('users', 'created', nullable=True, server_default=None, schema=app_schema)
    op.alter_column('owners', 'created', nullable=True, server_default=None, schema=app_schema)
    op.alter_column('maintainers', 'created', nullable=True, server_default=None, schema=app_schema)
    op.alter_column('groups', 'created', nullable=True, server_default=None, schema=app_schema)

    # ### end Alembic commands ###
